name: CI Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    
    timeout-minutes: 20
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #    with:
        # submodules: recursive

      # Runs a single command using the runners shell
      - name: Compiling repo
        run: |
          make clean
          make
  
  test:
    runs-on: self-hosted

    timeout-minutes: 20

    needs: build

    steps:
   
      # Checks VectorAdd of 1000 elements 
      - name: Checking Vector Add with 1000 elements
        run: |
          ./vector_add 1000 &> 1000.out 
          tail -n3 1000.out | diff .github/test/1000.solution -
        if: always()

      # Checks VectorAdd of 1000 elements 
      - name: Checking Vector Add with 10000 elements
        run: |
          ./vector_add &> 10000.out 
          tail -n3 10000.out | diff .github/test/10000.solution -
        if: always()
        
        
  cleanup:
    
    runs-on: self-hosted
    if: always()
    needs: [build,test]
    steps:
      - name: Clean up
        run: echo "Cleaning up previous run"; rm -rf "${{ github.workspace }}";

